### ISSUE TITLE
NGI0 - Updating licensing aspects according REUSE

### ISSUE THREAD

**Issue by lucaslasota** [AGProjects/sylk-mobile#1]
Hello,

aligned with the NGI0 initiative, I'd like to propose the adoption of REUSE specifications for improvement of copyright and license displaying. The [REUSE](https://reuse.software) specifications intend to make licensing easier, setting one way to display all license and copyright information direct on source files in a way that can be human- and machine-readable. 

Feel completely free to adopt them or not :)

## REUSE Features
- SPDX copyright and license comment headers for all files
- LICENSES directory with all licenses used on the repository
- DEP5 file to bulk-license entire directories 

## Example of implementation
For the repository [sylk-mobile](https://github.com/AGProjects/sylk-mobile), the majority of the source files has no copyright and license information. The repository contains no `LICENSE` file, although it is clear on `README`. Therefore, I would suggest the following measures:

1. Create a `LICENSES` directory in the project root and insert already the `GPL-3.0-or-later.txt` file in it. 
2. Add the comment headers for all relevant file. Example: In the file `sylk-mobile/Logger.js` you can add:

`// SPDX-FileCopyrightText: 2020 Adrian Georgescu <devel@ag-projects.com>`
`// SPDX-FileCopyrightText: 2020 Tijmen de Mes <devel@ag-projects.com>`
`// SPDX-License-Identifier: GPL-3.0-or-later`

## DEP5 file for bulk-licensing
In the repository there are some directories containing many files which may not be easy or practical to edit every file to contain a header. While doing this would be ideal, there is an alternative. By creating the file `.reuse/dep5` file on repository root. For example, the directory  `sylk-mobile/app/assets/images/` you can use the following `dep5` file:

```
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: Sylk Mobile
Upstream-Contact: Adrian Georgescu <devel@ag-projects.com>
Source: https://github.com/AGProjects/sylk-mobile/
 
Files: sylk-mobile/app/assets/images/*
Copyright: 2020 Dan Jenkins <devel@ag-projects.com> (or whoever is the copyright holder)
License: GPL-3.0-or-later

```
## Further REUSE compliance
We offer a [wide range of tools](https://reuse.software/dev/) to help you to implement semi-automatically the legal information, as well as to continuously check and display compliance with the REUSE guidelines.

In case you find REUSE useful for your workflow, you are most encouraged to adopt it. Feel free to follow up on that!

Thanks for the amazing job!

**PS**: Sorry for initiating an issue instead a pull request. Unfortunately I am not familiar with darcs as stated in your [contribution policy](https://sylkserver.com/download/#github).  Hope this contribution can be somehow useful for you! ;)

**Comment by adigeo** [comment]
I added the LICENSE file for clarity. The rest is too much work and cumbersome to spend time on as each file can become a can of worms. I hope you don't mind.
