### ISSUE TITLE
Unable to decrypt the git file

### ISSUE THREAD

**Issue by mrkerusi** [AGProjects/sylk-mobile#5]
hi Sylk Dev,

I would like to have copy of this build, but it seems like i'm unable to make the build in xcode because of missing files. i suspected some of the file is still encrypted. it was mention in the guide i should share my gpg key to anyone that has access to. may i know whom i can contact with to share my key and have access to the source file,

Thank You Very Much! :)

Regards,
Brightson.J 

![image](https://user-images.githubusercontent.com/58578547/112945621-1d0d4500-9167-11eb-95a1-d042333d3dd5.png)

**Comment by adigeo** [comment]
We do not keep any encrypted data inside the repo.
