### ISSUE TITLE
Missing GoogleInfo.plist file on Sylk-Mobile Build on Xcode

### ISSUE THREAD

**Issue by mrkerusi** [AGProjects/sylk-mobile#6]
Dear Sylk-mobile dev, I tried to build the Sylk-Mobile, but it seems like missing this particular file.

Regards,

Brightson.J

<img width="733" alt="Screenshot 2021-04-06 at 6 25 09 PM" src="https://user-images.githubusercontent.com/58578547/113697351-a7c0e780-9705-11eb-8c2a-c50a23205e71.png">

**Comment by adigeo** [comment]
There is nothing missing. We do not publish private information like account and passwords, they are not public.

If you want to build the software you must have Google and Apple developer accounts and use your own accounts and keys when building the software.
