### ISSUE TITLE
XMPP support?

### ISSUE THREAD

**Issue by poVoq** [AGProjects/sylk-mobile#7]
Would be cool if this could also connect to the wider XMPP federation.

**Comment by adigeo** [comment]
We are working on this, is almost working. I wish I could find a Jingle client to test with.

**Comment by poVoq** [comment]
Audio / Video chat (DTLS-SRTP) is now supported by several XMPP clients. Did you try Conversations:
https://f-droid.org/en/packages/eu.siacs.conversations/
Otherwise maybe https://movim.eu ? (you can use their hosted version)

Maybe also Gajim, but I think that doesn't have the most up to date implementation yet: https://gajim.org/

(The latest unreleased dev version of https://dino.im/ also supports it).

Edit: on iOS: https://siskin.im/

**Comment by adigeo** [comment]
Any interoperability issue belongs to the backend server, SylkServer. The client is abstract and has no idea about the protocols involved in the core network (SIP or XMPP).
